# Generated by Django 4.2.30 on 2026-07-09 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('research', 'Research')], max_length=20)),
                ('prompt', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
