# Generated by Django 4.2.30 on 2026-07-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_core', '0003_ratelimitbucket_alter_authtoken_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
